export enum ErrorCode {
    USER_UNAUTHORIZED = 'AUTH1001',
    TOKEN_EXPIRED = 'AUTH1002',
    USER_ROLE_FORBIDDEN = 'AUTH1003',
    COLLEGE_NAME_DUPLICATED = 'COL1001',
    ALREADY_SUBSCRIBED = 'SUB1001',
    ALREADY_UNSUBSCRIBED = 'SUB1002',
}
